version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: web
    build:
      context: ./
      dockerfile: Web/Dockerfile
    links:
    - db
    depends_on:
    - db
    networks:
    - local
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "R8PQW2vUjH"
    networks:
     - local
    ports:
     - "1433:1433"
  migrations:
    image: ${DOCKER_REGISTRY-}migrations
    container_name: migrations
    build:
      context: ./
      dockerfile: BooksBase.Migrations/Dockerfile
    links:
    - db
    depends_on:
    - db
    networks:
    - local
    environment:
    - "ConnectionStrings:DbConnection=Server=db;Database=booksBase;User=sa;Password=R8PQW2vUjH;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
  azurestorage:
    container_name: azurestorage
    image: "arafato/azurite:latest"
    ports:
     - "9569:10000"
     - "9570:10001"
     - "9571:10002"
    networks:
     - local
  azurefunctions:
    image: ${DOCKER_REGISTRY-}corefunctions
    container_name: azurefunctions
    environment:
    - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurestorage:10000/devstoreaccount1;QueueEndpoint=http://azurestorage:10001/devstoreaccount1;TableEndpoint=http://azurestorage:10002/devstoreaccount1;
    - QueueName=emails
    - SendGridApiKey
    - SenderEmail=aquarius96@wp.pl
    - SenderName=BooksBase
    build:
      context: ./BooksBase.CoreFunctions
      dockerfile: Dockerfile
    links:
     - azurestorage
    depends_on: 
     - azurestorage
    networks:
     - local
networks:
  local:
    driver: bridge